from . import lnl, attention

NODE_CLASS_MAPPINGS = lnl.NODE_CLASS_MAPPINGS | attention.NODE_CLASS_MAPPINGS
NODE_DISPLAY_NAME_MAPPINGS = (
    lnl.NODE_DISPLAY_NAME_MAPPINGS | attention.NODE_DISPLAY_NAME_MAPPINGS
)
