title: "Scrambled Attention"
description: "A very work in progress informal paper on Scrambled Attention Guidance"
theme: jekyll-theme-slate

markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM   # optional, if you prefer GitHub-Flavored Markdown
