# _config.yml
title: "Scrambled Attention"
description: "A very work in progress informal paper on Scrambled Attention guidance"
theme: jekyll-theme-slate
markdown: kramdown
kramdown:
#  input: GFM
  math_engine: mathjax